server:
  port: 8181

springdoc:
  api-docs:
    path: /v3/api-docs

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}

stripe:
  key: ${STRIPE_SECRET_KEY}

spring:

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: /.well-known/jwks.json
  #  jmx:
  #    enabled: true
  #    default-domain: authservice
    datasource:
  #    hikari:
  #      maximum-pool-size: 7
  #      register-mbeans: true
      url: jdbc:mysql://localhost:3306/venuehub
      username: ali
      password: "@Li4103568"
      driver-class-name: com.mysql.cj.jdbc.Driver
    quartz:
      properties:
        org.quartz.threadPool.threadCount: 5
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#        org.quartz.jobStore.dataSource: myDataSource
#        org.quartz.dataSource.myDataSource.driver: com.mysql.cj.jdbc.Driver
#        org.quartz.dataSource.myDataSource.URL: jdbc:mysql://localhost:3306/jobservice
#        org.quartz.dataSource.myDataSource.username: ali
#        org.quartz.dataSource.myDataSource.password: "@Li4103568"
      job-store-type: JDBC
    jpa:
      show-sql: false
      generate-ddl: true

      hibernate:
        ddl-auto: update

